theastropath/turbot

tests/test_turbot.py
turbot/__init__.py

Also fixes some places where we were not using `save_prices()` and some bad tests.

Oops command only for yourself.

---

.github/workflows/ci.yaml

Adding a github CI workflow to automatically run tests against PRs 🎉

Adds github ci workflow

---

.github/workflows/ci.yaml

Ok, this configuration should be good! 🎉 Needed to specify the python version in the right place.

Adds github ci workflow part 2

---

README.md
requirements/common.txt
requirements/dev.txt
tests/test_turbot.py
tox.ini
turbot/__init__.py
turbot/migrate.py

This commit also fixes all the issues these tools found.

Adds codebase tests

---

requirements/dev.txt
scripts/reqs.sh
scripts/update.sh
tests/test_turbot.py
turbot/__init__.py

- Adds some scripts to help deal with dependencies.
- Updates dependencies and fixes some code that doesn't pass lint with the new version of pyflakes.

Req scripts

---

tests/test_turbot.py
turbot/__init__.py
turbot/data/strings.yaml

Adds a `!predict` command that looks at your turnip history and gives you a link to a pre-filled turnip prediction calculator.
Link in screenshot: https://turnipprophet.io/?prices=107.........50.100

Adds predict command

---

turbot/__init__.py

Mutli-line descriptions in command functions contained linebreaks which were being copied into the help command, which meant that the lines didn't start with the > character which denotes a quote in Discord.  I stripped the newlines out of the descriptions and am letting Discord handle the linewrapping itself.
This made an issue with the pagination function apparent also.  Apparently trailing empty quote lines aren't rendered as quotes, and so there was a random > appearing where the !help command was split.  I adjusted the pagination so that it would ensure a page would never end with a trailing empty quote line and would instead push the line into the next page instead.

Corrected the linebreaks in the help command so that everything is quoted

---

tests/test_turbot.py
turbot/__init__.py

So as to avoid any future accidents, the reset command now creates a datestamped backup of the prices file.

Running the reset command now creates a datestamped backup of the prices file

---

turbot/__init__.py

!sell was comparing to the last !buy price unintentionally.  Now it will only compare to the last selling price.

Make sure sell command compares to another sell price

---

tests/test_turbot.py

Continuing to build the test suite out more and more. This adds a test for `get_last_price()` to avoid any future regressions if we have to modify it again for some reason.

Adds tests for get_last_price

---

tests/test_turbot.py
turbot/__init__.py

Adds command line support

---

tests/test_turbot.py
turbot/__init__.py

Fossilsearch didn't always output its header.  Also, made sure that it always gives its results first and then tells you what it didn't recognize.

Tweaked fossilsearch to have slightly more consistent output

---

.gitignore
README.md
turbot/__init__.py

The root directory was getting really crowded with config files, runtime files, temporary files, source files, etc... I just cleaned it up a bit.

Cleans up directories

---

.gitignore
tests/test_turbot.py
turbot/__init__.py
turbot/data/strings.yaml

**This change requires #43 to be merged first.**
Adds a user's preference file. For now we can use it to store a user's hemisphere choice. Later this could be expanded to support more things.

Adds user preferences

---

.gitignore
scripts/update_fish_data.py
tests/test_turbot.py
turbot/__init__.py
turbot/data/fish.csv
turbot/data/strings.yaml

**This change requires #44 to be merged first.**
Resolves #22

Fish command

---

turbot/__init__.py

As I learn more about how pandas work I realize some code could have been much cleaner.

Updates some pandas code to make it cleaner

---

tests/test_turbot.py
turbot/__init__.py
turbot/data/strings.yaml

**This PR builds upon the changes from https://github.com/theastropath/turbot/pull/49**
This adds the command `!timezone` which lets a user set their timezone preference. It also updates the `!predict` command to use that preference if it's available.

Tz aware predict

---

tests/test_turbot.py
turbot/__init__.py

Everything was passing in the tests because we never actually used the code path where the prices data already exists on disk and we try to load it. So I added a test for that and then fixed the bug.

Fixes a bug in price data loading

---

scripts/update_bugs_data.py
tests/test_turbot.py
turbot/__init__.py
turbot/data/bugs.csv
turbot/data/strings.yaml

Resolves https://github.com/theastropath/turbot/issues/46

Adds bug command

---

tests/test_turbot.py
turbot/__init__.py

The bestsell command being tz aware is pretty important b/c it lets you know how much longer that price is available... it might be worth it to add output like `... you have less than 3 hours left to buy turnips at this price!" or whatever.

Adds timezone aware best sell/buy

---

turbot/__init__.py

No tests... doesn't seem terribly worth it for this 🤷‍♀️

Adds timezone aware bugs/fish commands

---

.coveragerc
.github/workflows/ci.yaml
LICENSE.md
README.md
requirements/dev.txt
tests/test_turbot.py
tox.ini
turbot/__init__.py

Report is here: https://codecov.io/github/theastropath/turbot/commit/ad92ee43b037cc6bb5a4fb20eb0050cb74302aec
Not sure why the codecov comment is messed up here, I think will start working correctly once this gets merged maybe? 🤞The report itself looks fine.

Adds codecov

---

tests/test_turbot.py
turbot/__init__.py

Don't appear in the results if you've never collected a fossil.

Limit list needed to collectors

---

tests/test_turbot.py
turbot/__init__.py

Resolves https://github.com/theastropath/turbot/issues/73

Ignore caps in commands

---

README.md
turbot/__init__.py

Resolves https://github.com/theastropath/turbot/issues/15

Adds turbot token env

---

scripts/update_fish_data.py
tests/test_turbot.py
turbot/data/fish.csv

Updates the update script and fish data to have image links. Not used for anything yet, but could be used to improve the output of the `!fish` command now that we have it.

Capture fish images

---

scripts/update_bugs_data.py
tests/test_turbot.py
turbot/__init__.py
turbot/data/bugs.csv
turbot/data/strings.yaml

Use bugs images in details response

---

CONTRIBUTING.md
README.md

As recommended by https://github.com/theastropath/turbot/community

Adds a contributing doc

---

src/turbot/__init__.py
src/turbot/data/strings.yaml
tests/test_turbot.py

Resolves https://github.com/theastropath/turbot/issues/101

Adds buy/sell at day and time

---

poetry.lock
pyproject.toml
src/turbot/__init__.py
src/turbot/data/strings.yaml
tests/test_turbot.py

Humanize datetimes on display

---

scripts/sort_strings.py
src/turbot/data/strings.yaml
tests/test_turbot.py

Helps prevent merge conflicts and now it doesn't need to be done manually anymore 🎉

Sort strings automatically

---

README.md
src/turbot/__init__.py
src/turbot/data/strings.yaml
tests/snapshots/test_on_message_info_0.txt
tests/test_turbot.py

Resolves https://github.com/theastropath/turbot/issues/109

Adds island command and user embed

---

README.md
src/turbot/__init__.py
src/turbot/data/strings.yaml
tests/snapshots/test_on_message_info_0.txt
tests/test_turbot.py

Resolves https://github.com/theastropath/turbot/issues/108

Adds friend and fruit commands

---

src/turbot/data/strings.yaml
tests/test_turbot.py

Resolves https://github.com/theastropath/turbot/issues/61

Bold user names in best commands

---

tests/snapshots/test_on_message_new_first_day_0.txt
tests/snapshots/test_on_message_new_first_day_1.txt
tests/test_turbot.py

Also adds some helpful semantic fixtures around bugs tests.

Adds test for first of month

---

README.md
src/turbot/__init__.py
src/turbot/data/strings.yaml
tests/snapshots/test_on_message_info_0.txt
tests/test_turbot.py

Adds nickname command

---

README.md

Updates screenshot

---

README.md
src/turbot/__init__.py
tests/snapshots/test_on_message_about_0.txt
tests/snapshots/test_on_message_bug_search_leaving_0.txt
tests/snapshots/test_on_message_bug_search_query_few_0.txt
tests/snapshots/test_on_message_bugs_case_insensitive_0.txt
tests/snapshots/test_on_message_fish_case_insensitive_0.txt
tests/snapshots/test_on_message_fish_search_leaving_0.txt
tests/test_turbot.py

Adds about command

---

CONTRIBUTING.md
README.md
scripts/publish.sh
tests/snapshots/test_on_message_about_0.txt

Fixes the build on `master` and adds a script to help ensure this process goes smoothly in the future.

Publish script

---

src/turbot/__init__.py
src/turbot/data/strings.yaml
tests/test_turbot.py

Handle info for user w/o prefs

---

src/turbot/__init__.py
src/turbot/data/strings.yaml
tests/snapshots/test_on_message_info_0.txt
tests/test_turbot.py

Adds creator command

---

README.md
src/turbot/__init__.py
src/turbot/data/strings.yaml
tests/snapshots/test_on_message_help_0.txt
tests/snapshots/test_on_message_help_1.txt
tests/snapshots/test_on_message_turnippattern_happy_paths_0.txt
tests/snapshots/test_on_message_turnippattern_happy_paths_1.txt
tests/snapshots/test_on_message_turnippattern_happy_paths_2.txt
tests/test_turbot.py

**depends on #142 being merged first**
Creating new commands every time we add a user preference is getting to be a pain. This consolidates it all into a `!pref` command and cleans up a ton of cruft and duplicated code.

Pref command

---

src/turbot/__init__.py
tests/test_turbot.py

Resolves https://github.com/theastropath/turbot/issues/169

Adds logic to discover timezone names

---

src/turbot/__init__.py
tests/test_turbot.py

Resolves https://github.com/theastropath/turbot/issues/168

Adds fuzzy pref names

---

scripts/update_fossils_assets.py

Resolves #162.
I had to edit the wiki for this script to work, they had some incorrect names there!

Adds fossils update script

---

src/turbot/__init__.py
src/turbot/assets/strings.yaml
tests/test_turbot.py

Resolves https://github.com/theastropath/turbot/issues/60
Resolves https://github.com/theastropath/turbot/issues/62

Show remaining time on best command

---

tests/test_turbot.py

Resolves https://github.com/theastropath/turbot/issues/155
I couldn't actually reproduce this so I think maybe it's not actually a bug, but just in case I added a test case for it.

Adds test for early congrats

---

src/turbot/__init__.py
src/turbot/data.py

**Description**
Reduces the number of calls to `getattr()` just because they're kinda ugly.
**Checklist**

Reduce calls to getattr
