tests/test_turbot.py, turbot/__init__.py
Keeps the fossil and price data in memory so we don't have to keep loading the files over and over again. Whenever we change the data we make sure to save the file so that if turbot exits it can just re-load the data one from file at start up time.
=> In memory optimization.

.github/workflows/ci.yaml, requirements/dev.txt, tests/test_turbot.py, tox.ini, turbot/__init__.py
I was having issues with flake8-black actually picking up things like unused imports. I don't know but it's weird and a dependency we don't actually need. Refactored the codebase tests to not need it. This also cleans up docstrings as well thanks to fancy `inspect.cleandoc()` function that I just learned about.
I also made it so CI runs on push **and pull requests** because before it was only running on pushes to my fork, which isn't what we want at all.
=> Remove flake8 black

turbot/__init__.py, turbot/data/strings.yaml
Added feedback to let you know what fossils !fossilsearch was unable to find when handling a request.  Also, if no buy price was found by the !predict command, it only returned a string and no value for the attachment (None).  I added the attachment value so that it wouldn't fail.
=> Add unrecognized fossil feedback to fossilsearch and correct error if predict can't find a buy price

tests/test_turbot.py, turbot/__init__.py, turbot/data/strings.yaml
**addc854363aaec3e14694b416b18aaaf5c92a667 Delete theirs concern from fossilsearch**
I agree, a couple users already tried to use it this way and were
surprised when it didn't work. We can just get rid of the `theirs`
variable here and rename things so the better represent the data they
contain.
**3756b646a9595d0f4b3e67cdf7cc7aef59eaa2e9 More information from fossilsearch response**
When there's a combination of no fossils that are needed plus a couple
that are invalid you would only get the list of invalid fossils but no
indication that the other fossils were not needed.
I changed the code a bit so that you get both a list of things that
aren't needed and the list of things that were invalid.
Also note that in Python you can always do `if some_list` to check if
the list is empty. Less …
=> Invalid fossil search tests

tests/test_turbot.py, turbot/__init__.py
The !hello and !lookup commands were only ever really intended as test commands when I was just getting the bot up and running.  Removing them since they serve no real purpose.
=> remove hello and lookup commands

tests/test_turbot.py, turbot/data/strings.yaml
**3ce90e643ddcbf3ab8994f0656ecdc17348961a0 Removes unused strings**
**b66942290058266c0d9a95a7c9d6247dd98f4132 Fixes a bug in the a test case**
**4b6678a6bdee27b4e255928d37e19fafffc1b33b Adds a test to check for unused strings**
**c7527178c2022f9c93858695ad5f1b0eb5128b78 Adds missing tests for two strings**
These strings were being used in the application, but there was no test for them yet.
=> Test strings

tests/test_turbot.py
This fixes things so that `tox -- -k codebase` actually works correctly.
=> Breaks out meta test to its own class

scripts/update_fish_data.py, tests/test_turbot.py, turbot/__init__.py, turbot/data/fish.csv, turbot/data/strings.yaml
You can now search for fish with `!fish substring`. It'll find any fish with the given substring in their names. The results returned by a search give a little more details than the generic `!fish` command with no parameters.
You can also search for the special query `leaving` and it will look for fish that are not available next month.
Also I made all the data lowercase b/c it makes the code a lot easier. We can transform the data to capitalize it or whatever at display time. This better follows the best practice pattern of keeping things in their canonical form in the database and then transforming that data when displayed to the user.
> **IMPORTANT: We need to go into `db/users.csv` and make sure to lowercase everything in there after installing this change. Otherwise the fish command …
=> Adds search to fish command

tests/test_turbot.py, turbot/__init__.py
Refactored mock classes by giving them all the prefix `Mock` to make it super clear what's going on in stack traces when there's an error. Stripped down the mocks as much as I could and made them independent of module level data. Factored out the channel mock to a fixture to reduce the number of lines of redundant code. Plus some other changes I'll call out in comments on the diffs.
=> Refactor mocks

tests/test_turbot.py, turbot/__init__.py
**Builds upon work from https://github.com/theastropath/turbot/pull/52**
Fixes the case where turbot was responding to things like just a single `!` in chat.
=> Handle empty request

.github/workflows/ci.yaml, README.md
When I first named the workflow I didn't know the name would be the text in the badge here:
Would make a lot more sense for that badge to say `build: passing` I think.
=> Rename build workflow

src/turbot/__init__.py, src/turbot/data/strings.yaml, tests/test_turbot.py
In the future we can add things to a user's info, for example:
- Island Name https://github.com/theastropath/turbot/issues/109
- Switch Friend Code https://github.com/theastropath/turbot/issues/108
- Island Rules https://github.com/theastropath/turbot/issues/100
- Wants https://github.com/theastropath/turbot/issues/110
- Sall/Catalog Items https://github.com/theastropath/turbot/issues/18
- Etc...
=> Adds user !info command

scripts/publish.sh
If the publish command fails we need to roll back the commit so that the script is transactional. We also need to make absolutely sure that the -e and -u options are set correctly. It's safer to do this in a separate set command than rely on shell opts working properly (these have been known to be flaky in certain versions of bash for example).
=> Transactional publish script

poetry.lock, pyproject.toml, src/turbot/__init__.py
Automatically reload the bot whenever the source code changes if you use the `--dev` option. Also picks up changes to data files if they change during runtime.
=> Adds auto-reload dev option

README.md, src/turbot/__init__.py, src/turbot/data/strings.yaml, tests/snapshots/test_on_message_help_0.txt, tests/snapshots/test_on_message_help_1.txt, tests/snapshots/test_on_message_turnippattern_happy_paths_0.txt, tests/snapshots/test_on_message_turnippattern_happy_paths_1.txt, tests/snapshots/test_on_message_turnippattern_happy_paths_2.txt, tests/test_turbot.py
Removes the turnippattern command as `!predict` and `!graph username` give much better information, I'm also a bit worried that sometimes turnippattern can be inaccurate. Regardless, no one seems to use it anymore 🤷‍♀️ 
Also I removed the weird magic where turbot automatically found methods with names like `foo_command` and instead introduced the more explicit `@command` decorator that lets you say exactly what methods should be considered commands. This also cleans up the logic in `process()` and `help()` and in the test suite.
Added a codebase test to check that the readme references all the commands that are available after noticing that we didn't have a reference to `!bestbuy` in there.
=> Cleans up commands

README.md, src/turbot/__init__.py, src/turbot/data/strings.yaml, tests/snapshots/test_on_message_help_0.txt, tests/snapshots/test_on_message_help_1.txt, tests/snapshots/test_on_message_turnippattern_happy_paths_0.txt, tests/snapshots/test_on_message_turnippattern_happy_paths_1.txt, tests/snapshots/test_on_message_turnippattern_happy_paths_2.txt, tests/test_turbot.py
**depends on #141 being merged first**
Changes the following commands:
- The `!graph` command is now only used for getting a historical graph for all users.
- The `!predict` command is the one-stop-shop for all things related to stalk market predictions, it gives you the graph embed and the turnipprophet link in a much prettier format than before.
=> Simplify graph predict

src/turbot/__init__.py, tests/test_turbot.py
Found a bug where `!buy 90 sunday morning` would set the buy price's timestamp to the following Sunday instead of the previous Sunday. This fixes it and adds a test to ensure it doesn't regress.
=> Fixes an issue with buy at set time

src/turbot/__init__.py
Makes it so just importing turbot or running `turbot --version` doesn't take forever because it's loading up data files.
=> Lazy load application data

.coveragerc, src/turbot/__init__.py, tests/test_turbot.py
Sometimes the turnips library fails to generate a graph. In that case, don't show it. We still have the turnipprophet.io link to provide to the user (and sometimes, depending on how wild the user's data it, even that website won't show a valid graph).
Resolves #151
=> Don't show error graphs

src/turbot/__init__.py, src/turbot/data/strings.yaml, tests/snapshots/test_on_message_count_no_params_0.txt, tests/snapshots/test_on_message_help_0.txt, tests/test_turbot.py
Makes `!count` by itself return results for yourself like how the other commands related to collectables work.
=> Count defaults to yourself

.github/workflows/ci.yaml, CONTRIBUTING.md, DOCKER.md, HEROKU.md, README.md, app.json, poetry.lock, pyproject.toml, scripts/create_db_revision.py, src/turbot/__init__.py, src/turbot/assets/alembic.ini, src/turbot/assets/strings.yaml, src/turbot/data.py, src/turbot/versions/versions/33940279af35_keep_track_of_authorized_channels_per_.py, src/turbot/versions/versions/9b107d322c46_use_bigint_for_author_ids.py, tests/snapshots/test_on_message_help_0.txt, tests/snapshots/test_on_message_help_1.txt, tests/test_turbot.py
When I started testing using PostgreSQL as the backend it became obvious quickly that some changes would need to be made to accommodate it.
- The database adapter for PostgreSQL, `psycopg2`, needed to be added.
- The `GROUP BY` query in sqlite doesn't work in a real database like PostgreSQL, so I re-wrote it in such a way that it will work on both sqlite and real databases.
- Since sqlite treats all integral data types the same, it didn't matter if we used `INTEGER` or `BIGINT` for the `author` columns. However in any real database you will need `BIGINT` for these. So I added a migration to alter those columns. This doesn't actually affect the behavior of sqlite at all, but it makes things work on PostgreSQL.
- If you're using PostgreSQL for tests you have to ensure that the tests have a …
=> Changes to support postgresql
